apiVersion: apps/v1
kind: Deployment
metadata:
  name: contador-deployment
  labels:
    app: contador
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contador
  template:
    metadata:
      labels:
        app: contador
    spec:
      containers:
        - name: contador
          image: anaalonso8/contador:1.0
          imagePullPolicy: IfNotPresent
